import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ProfileButton } from "@/components/ProfileButton";
import { LocalStorageProvider } from "@/components/LocalStorageProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "ZenDesk Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <LocalStorageProvider>
          <TooltipProvider>
            <div className="flex items-center justify-between border-b px-6 py-3">
              <h1 className="text-xl font-semibold">OHF Partners</h1>
              <ProfileButton />
            </div>
            {children}
          </TooltipProvider>
        </LocalStorageProvider>
      </body>
    </html>
  );
}
